modLoader="javafml"

loaderVersion="[34,)"

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-world-bizzare-mod"

[[mods]]

modId="wonderful_world"

version="1.16.3-0.6.0"

displayName="Wonderful World"

updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-world-bizzare-mod"

displayURL="https://www.curseforge.com/minecraft/mc-mods/wonderful-world-bizzare-mod"

logoFile="logo.png"

credits="Thanks for all your suport!"

authors="Majrusz"

description='''
Great minimalist mod!
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
