modLoader="javafml"
loaderVersion="[35,)"
license="MIT License"
issueTrackerURL="https://github.com/Majrusz/WonderfulEnchantmentsMod/issues"

[[mods]]
    modId="wonderful_enchantments"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="${mod_update_json_url}"
    displayURL="${mod_display_url}"
    logoFile="logo.png"
    credits="${mod_credits}"
    authors="${mod_author}"
    description='''${mod_description}'''

[[dependencies.wonderful_enchantments]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wonderful_enchantments]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.wonderful_enchantments]]
    modId="majrusz_library"
    mandatory=true
    versionRange="[1.0.0,2.0.0)"
    ordering="NONE"
    side="BOTH"